# Generated by Django 3.1.7 on 2021-03-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitas',
            new_name='Visita',
        ),
    ]
