# Generated by Django 3.1.7 on 2021-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_auto_20210324_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='visita',
            name='timestamp_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
